import { ImageName } from './image-names'

export const imageMappings: Record<ImageName, string> = {
  nail: 'https://textpro.me/create-an-online-3d-nail-art-text-effect-1148.html',
  thunder: 'https://textpro.me/create-3d-thunder-text-effects-online-1147.html',
  moss: 'https://textpro.me/create-realistic-3d-moss-text-effects-online-1145.html',
  black: 'https://textpro.me/shiny-black-3d-text-effect-generator-1143.html',
  cyber: 'https://textpro.me/create-a-glowing-3d-neon-light-text-effect-1142.html',
  shadow: 'https://textpro.me/create-a-gradient-text-shadow-effect-online-1141.html',
  iphone15: 'https://textpro.me/create-a-titanium-text-effect-for-the-iphone-15-introduction-event-1140.html',
  bigsale: 'https://textpro.me/sale-promotion-ads-3d-text-effect-1136.html',
  pokemon: 'https://textpro.me/create-pokemon-logo-style-text-effect-online-1134.html',
  friday: 'https://textpro.me/neon-light-style-3d-text-effect-online-1132.html',
  naruto: 'https://textpro.me/generate-naruto-logo-style-text-effect-online-1125.html',
  cartoon: 'https://textpro.me/create-3d-cartoon-text-effect-online-1120.html',
  liquid: 'https://textpro.me/create-3d-liquid-metal-text-effect-1112.html',
  cage: 'https://textpro.me/create-cage-text-effect-online-1110.html',
  metal: 'https://textpro.me/create-3d-metallic-text-with-details-online-1108.html',
  party: 'https://textpro.me/party-text-effect-with-the-night-event-theme-1105.html',
  bornpink: 'https://textpro.me/create-blackpink-s-born-pink-album-theme-logo-online-1092.html',
  typhography: 'https://textpro.me/create-artistic-typography-online-1086.html',
  neonstyle: 'https://textpro.me/create-gradient-neon-light-text-effect-online-1085.html',
  blackpink: 'https://textpro.me/create-neon-light-blackpink-logo-text-effect-online-1081.html',
  slicedtext: 'https://textpro.me/create-light-glow-sliced-text-effect-online-1068.html',
  batman: 'https://textpro.me/make-a-batman-logo-online-free-1066.html',
  neonlightonbrick: 'https://textpro.me/create-neon-light-on-brick-wall-online-1062.html',
  black2: 'https://textpro.me/create-a-metallic-text-effect-free-online-1041.html',
  demon: 'https://textpro.me/create-green-horror-style-text-effect-online-1036.html',
  magma: 'https://textpro.me/create-a-magma-hot-text-effect-online-1030.html',
  neonlight: 'https://textpro.me/create-3d-neon-light-text-effect-online-1028.html',
  glitch: 'https://textpro.me/create-impressive-glitch-text-effects-online-1027.html',
  neondevil: 'https://textpro.me/create-neon-devil-wings-text-effect-online-free-1014.html',
  blackpink2: 'https://textpro.me/create-blackpink-logo-style-online-1001.html',
  glitcheffect: 'https://textpro.me/create-glitch-text-effect-style-tik-tok-983.html',
  neongalaxy: 'https://textpro.me/neon-light-text-effect-with-galaxy-style-981.html',
  pornhub: 'https://textpro.me/generate-a-free-logo-in-pornhub-style-online-977.html',
  marvelstudio: 'https://textpro.me/create-logo-style-marvel-studios-online-971.html',
  matrix: 'https://textpro.me/matrix-style-text-effect-online-884.html',
  thunderneon: 'https://textpro.me/create-thunder-text-effect-online-881.html',
  neon: 'https://textpro.me/neon-text-effect-online-879.html',
  roadwarning: 'https://textpro.me/road-warning-text-effect-878.html',
  bokeh: 'https://textpro.me/bokeh-text-effect-876.html',
  advancedglow: 'https://textpro.me/free-advanced-glow-text-effect-873.html',
  thewall: 'https://textpro.me/break-wall-text-effect-871.html',
  ice: 'https://textpro.me/ice-cold-text-effect-862.html'
}