export type ImageName = 'nail' | 'thunder' | 'moss' | 'black' | 'cyber' | 'shadow'
  | 'iphone15' | 'bigsale' | 'pokemon' | 'friday' | 'naruto' | 'cartoon' | 'liquid'
  | 'cage' | 'metal' | 'party' | 'bornpink' | 'typhography' | 'neonstyle' | 'blackpink'
  | 'slicedtext' | 'batman' | 'neonlightonbrick' | 'black2' | 'demon' | 'magma'
  | 'neonlight' | 'glitch' | 'neondevil' | 'blackpink2' | 'glitcheffect' | 'neongalaxy'
  | 'pornhub' | 'marvelstudio' | 'matrix' | 'thunderneon' | 'neon' | 'roadwarning'
  | 'bokeh' | 'advancedglow' | 'thewall' | 'ice'
